('Absolute Duo'),
('ACCA: 13-ku Kansatsu-ka'),
('Action Heroine Cheer Fruits'),
('Aho Girl'),
('Akagami no Shirayuki-hime'),
('Akagami no Shirayuki-hime S2'),
('Ajin S2'),
('Akame ga Kill'),
('Akanesasu Shoujo'),
('Akatsuki no Yona'),
('Akuma no Riddle'),
('Aldnoah.Zero'),
('Aldnoah Zero S2'),
('Alice to Zouroku'),
('All Out!!'),
('Amaama to Inazuma'),
('Amagi Brilliant Park'),
('Amanchu!'),
('Angolmois: Genkou Kassenki'),
('Anima Yell!'),
('Anne-Happy'),
('Ansatsu Kyoushitsu'),
('Ansatsu Kyoushitsu S2'),
('Ao Haru Ride'),
('Aoharu x Kikanjuu'),
('Ao no Exorcist: Kyoto Fujouou-hen'),
('Ao no Kanata no Four Rhythm'),
('Aoki Hagane No Arpeggio Ars Nova'),
('Arslan Senki'),
('Asobi Asobase'),
('Atelier Escha & Logy'),
('Atom: The Beginning'),
('Avatar: The Legend of Korra Book 3'),
('Avatar: The Legend of Korra Book 4'),
('B-Project: Kodou*Ambitious'),
('Baby Steps'),
('Basilisk: Ouka Ninpouchou'),
('Bakumatsu'),
('Ballroom e Youkoso'),
('Banana Fish'),
('Barakamon'),
('Battery'),
('Bayonetta: Bloody Fate Movie'),
('Beatless'),
('Beelzebub-jou no Okinimesu mama'),
('Black Bullet'),
('Black Clover'),
('Blade & Soul'),
('Blood Lad'),
('Bloodivores'),
('Blend S'),
('Brave Witches'),
('Break Blade (TV)'),
('Brothers Conflict'),
('Boku dake ga Inai Machi'),
('Boku no Hero Academia'),
('Boku no Hero Academia S2'),
('Boku no Hero Academia S3'),
('UQ Holder!: Mahou Sensei Negima! 2'),
('Bokura wa Minna Kawaisou'),
('Bubuki Buranki'),
('Bubuki Buranki: Hoshi no Kyojin'),
('Buddy Complex'),
('Bungou Stray Dogs'),
('Bungou Stray Dogs S2'),
('Busou Shoujo Machiavellianism'),
('Caligula'),
('Captain Earth'),
('Captain Tsubasa 2018'),
('Cardcaptor Sakura: Clear Card-hen'),
('Chaos Dragon: Sekiryuu Seneki'),
('ChaoS;Child'),
('Chain Chronicle: Haecceitas no Hikari'),
('Charlotte'),
('Choujigen Game Neptune'),
('Chuunibyou demo koi ga shitai! Ren'),
('Chio-chan no Tsuugakuro'),
('Classroom☆Crisis'),
('Clockwork Planet'),
('Comet Lucifer'),
('Conception'),
('Concrete Revolutio: Choujin Gensou'),
('Concrete Revolutio: Choujin Gensou – The Last Song'),
('Coppelion'),
('Daitoshokan no Hitsujikai'),
('Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka Gaiden: Sword Oratoria'),
('D-Frag!'),
('D.Gray-man Hallow'),
('Dagashi Kashi'),
('Dagashi Kashi S2'),
('Danganronpa 3: The End of Kibougamine Gakuen – Mirai-hen'),
('Danganronpa 3: The End of Kibougamine Gakuen – Zetsubou-hen'),
('Darling in the FranXX'),
('Death March kara Hajimaru Isekai Kyousoukyoku'),
('Death Parade'),
('Demi-chan wa Kataritai'),
('Denki-gai no Honya-san'),
('Denpa Kyoushi'),
('Date A Live S2'),
('91 Days'),
('Diabolik Lovers'),
('Diamond no Ace'),
('Diamond no Ace S2'),
('Dimension W'),
('Dive!!'),
('Divine Gate'),
('Dog Days S3'),
('Double Decker! Doug & Kirill'),
('DRAMAtical Murder'),
('Dragon Ball Super'),('Dragon Ball Heroes'),
('Dragon Ball Kai (2014)'),
('Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka'),
('Durarara!!x2 Shou'),
('Durarara!!x2 Ten'),
('Durarara!!x2 Ketsu'),
('elDLIVE'),
('Eromanga-sensei'),
('Etotama'),
('Evil or Live'),
('fairy tail'),
('Fantasista Doll'),
('Fate/Apocrypha'),
('Fate/kaleid liner Prisma☆Illya'),
('Fate/Stay Night Unlimited Blade Works'),
('Fate/stay night: Unlimited Blade Works S2'),
('Flip Flappers'),
('Flying Witch'),
('Free!'),
('Free! Eternal Summer'),
('Free!: Dive to the Future'),
('Fukumenkei Noise'),
('Fuuka'),
('Fukigen na Mononokean'),
('Fune wo Amu'),
('Gabriel DropOut'),
('Gamers!'),
('Gakkou Gurashi!'),
('Gakuen Babysitters'),
('Gakuen Basara'),
('Gakusen Toshi Asterisk'),
('Gakusen Toshi Asterisk S2'),
('Galilei Donna'),
('Grancrest Senki'),
('Gangsta'),
('Garo: Honoo no Kokuin'),
("Gate: Jieitai Kanochi nite, Kaku Tatakaeri"'),
("Gate: Jieitai Kanochi nite, Kaku Tatakaeri – Enryuu-hen"'),
('Gatchaman Crowds'),
('Gatchaman Crowds Insight'),
('Gegege no Kitarou (2018)'),
('Gekkan Shoujo Nozaki-kun'),
('Genei wo Kakeru Taiyou'),
('Genshiken Nidaime'),
('Ghost in the Shell: Arise – Alternative Architecture'),
('Ginga Kikoutai Majestic Prince'),
('Gingitsune'),
('Gin no Guardian'),
('Gin no Guardian S2'),
('Gin no Saji'),
('Gintama° (2015)'),
('Gintama (2017)'),
('Gintama. (2017)'),
('Gintama.: Shirogane no Tamashii-hen'),
('Glasslip'),
('Goblin Slayer'),
('Gochuumon wa Usagi desu ka?'),
('God Eater'),
('Golden Kamuy'),
('Golden Kamuy S2'),
('Golden Time'),
('Gokukoku no Brynhildr'),
('Grancrest Senki'),
('Grand Blue'),
('Granblue Fantasy The Animation'),
('Grisaia no Kajitsu'),
('Grisaia no Rakuen'),
('Gugure! Kokkuri-san'),
('Gundam Build Divers'),
('Gundam Build Fighter'),
('Gundam Build Fighters Try'),
('Gunslinger Stratos: The Animation'),
('Hai to Gensou no Grimgar'),
('Haikyuu'),
('Haikyuu S2'),
('Hakumei to Mikochi'),
('Hajime No Ippo Rising'),
('Hamatora The Animation'),
('Handa-kun'),
('Hanebado!'),
('Harukana Receive'),
('Haruchika: Haruta to Chika wa Seishun Suru'),
('Hakata Tonkotsu Ramens'),
('Hatsukoi Monster'),
('Hanayamata'),
('Heavy Object'),
('Hello!! Kiniro Mosaic'),
('HenNeko'),
('Hibike! Euphonium'),
('Hibike! Euphonium S2'),
('Hidan no Aria AA'),
('Himouto! Umaru-chan'),
('Himouto! Umaru-chan R'),
('Hina Logi: From Luck & Logic'),
('Hinako Note'),
('Hinamatsuri'),
('Hitsugi no Chaika'),
('Hitsugi no Chaika: Avenging Battle'),
('Hoozuki no Reitetsu'),
('Hoozuki no Reitetsu 2'),
('Hundred'),
('Imocho'),
('Imouto sae Ireba Ii.'),
('Inu to Hasami wa Tsukaiyou'),
('Inou-Battle wa Nichijou-kei no Naka de'),
('Isekai Shokudou'),
('Isekai Maou to Shoukan Shoujo no Dorei Majutsu'),
('Island'),
('Ito Junji: Collection'),
('Inuyashiki'),
('Irozuku Sekai no Ashita kara'),
('Isekai wa Smartphone to Tomo ni'),
('Isuca'),
('Isshuukan Friends'),
('IS: Infinite Stratos 2'),
('Jigoku Shoujo: Yoi no Togi'),
('Jikan no Shihaisha'),
('Jitsu wa Watashi wa'),
('JoJo no Kimyou na Bouken: Diamond wa Kudakenai'),
('Just Because!'),
('Juuni Taisen'),
('Juuou Mujin no Fafnir'),
('Joukamachi no Dandelion'),
('Junketsu no Maria'),
('K Return of Kings'),
('Kakegurui'),
('Kakuriyo no Yadomeshi'),
('Kanojo ga Flag wo Oraretara'),
('Kamisama no Inai Nichiyoubi'),
('Kantai Collection'),
('Karakai Jouzu no Takagi-san'),
('Katsugeki/Touken Ranbu'),
('Kaze ga Tsuyoku Fuiteiru'),
('Keppeki Danshi! Aoyama-kun'),
('Koi to Uso'),
('Kobayashi-san Chi no Maid Dragon'),
('Konbini Kareshi'),
('Kami nomi zo Shiru Sekai'),
('Kekkai Sensen'),
('Kekkai Sensen & Beyond'),
('Kidou Senshi Gundam: Tekketsu no Orphans'),
('Kidou Senshi Gundam: Tekketsu no Orphans S2'),
('Kill la Kill'),
('Kindaichi Case File Return'),
('Kitakubu Katsudou Kiroku'),
('Kimi No Iru Machi'),
('Kiniro Mosaic'),
('Kishuku Gakkou no Juliet'),
('Kiznaiver'),
('Kiseijuu: Sei no Kakuritsu'),
('Knight’s & Magic'),
('Koi wa Ameagari no You ni'),
('Kokkoku'),
('Kono Bijutsubu ni wa Mondai ga Aru!'),
('Kono Subarashii Sekai ni Shukufuku wo!'),
('Kono Subarashii Sekai ni Shukufuku wo! S2'),
('Koufuku Graffiti'),
('Kujira no Kora wa Sajou ni Utau'),
('Kuromukuro'),
('Kuroko no Basuke 2'),
('Kuroko no Basket S3'),
('Kuroshitsuji: Book of Circus'),
('Kuusen Madoushi Kouhosei no Kyoukan'),
('Kyoukai no Kanata'),
('Kyoto Teramachi Sanjou no Holmes'),
('Kyoukai no Rinne'),
('Kyoukai no Rinne S2'),
('Kyoukai no Rinne'),
('Kyoukai no Rinne'),
('Last Period: Owarinaki Rasen no Monogatari'),
('Little Busters!: Refrain'),
('Little Witch Academia (2017)'),
('Locodol'),
('Log Horizon'),
('Log Horizon S2'),
('Long Riders!'),
('Lord of Vermilion: Guren no Ou'),
('Lostorage Incited WIXOSS'),
('Love Lab'),
('Love Live! School Idol Project S2'),
('Love Live! Sunshine!!'),
('Love Live! Sunshine!! S2'),
('Love Stage!!'),
('Luck & Logic'),
('Macross Delta'),
('Madan no Ou to Vanadis'),
('Made in Abyss'),
('Mahou Sensou'),
('Mahou Shoujo Ikusei Keikaku'),
('Mahouka Koukou no Rettousei'),
('Mahou Shoujo Lyrical Nanoha ViVid'),
('Mahoutsukai no Yome'),
('Mayoiga'),
('Meganebu!'),
('Magic-Kyun! Renaissance'),
('Mekaku City Actors'),
('Majin Bone'),
('Major 2nd (TV)'),
('Makai Ouji'),
('Magi The Kingdom Of Magic'),
('Masamune-kun no Revenge'),
('Marginal#4: Kiss kara Tsukuru Big Bang'),
('(Megalo Box'),
('Mikakunin de Shinkoukei'),
('Mikagura Gakuen Kumikyoku'),
('Miss Monochrome'),
('Mitsuboshi Colors'),
('Miira no Kaikata'),
('Mushishi Zoku Shou'),
('Mob Psycho 100'),
('Monster Hunter Stories: Ride On'),
('Nana Maru San Batsu'),
('Nanbaka'),
('Nanbaka'),
('Nagato Yuki-chan no Shoushitsu'),
('Nanatsu no Taizai'),
('Nanatsu no Taizai: Imashime no Fukkatsu'),
('Naruto Shippuden'),
('Natsume Yuujinchou Go'),
('Natsume Yuujinchou Roku'),
('Netoge no Yome wa Onnanoko ja Nai to Omotta?'),
('Net-juu no Susume'),
('New Game!'),
('Nisekoi'),
('Nisekoi S2'),
('No Game No Life'),
('Nobunagun'),
('Nobunaga the Fool'),
('Norn9: Norn+Nonet'),
('NouKome'),
('Nourin'),
('Non Non Biyori'),
('Non Non Biyori Repeat'),
('Noragami'),
('Noragami Aragoto'),
('Nurse Witch Komugi-chan R'),
('Occultic;Nine'),
('Anime One Punch Man'),
('One Piece'),
('Onihei'),
('Ookami Shoujo to Kuro Ouji'),
('Orange'),
('oreimo'),
('Oregairu S2'),
('Osomatsu-san'),
('Osomatsu-san S2'),
('Ousama Game'),
('Oushitsu Kyoushi Haine'),
('Outbreak Company'),
('Overlord'),
('Overlord S2'),
('Overlord S3'),
('Owari no Seraph'),
('Owari no Seraph: Nagoya Kessen-hen'),
('Persona 4 The Golden Animation')
